---
- import_playbook: library/install_docker.yml
- import_playbook: library/init_geth.yml
- hosts: nodes
  become: true
  tasks:
  - name: Configuring docker-compose.yml
    template:
        src: templates/{{template_folder}}/docker-compose.yml.j2
        dest: /home/{{USERNAME}}/docker-compose.yml
    when: ACCOUNT_ID is defined

  - name: Configuring genesis.json
    template:
        src: templates/{{template_folder}}/genesis.json.j2
        dest: /home/{{USERNAME}}/node/genesis.json
    when: ACCOUNT_ID is defined
  
  - name: Init geth node with genesis
    shell: "docker run -v /home/{{USERNAME}}:/home/{{USERNAME}} jmank88/geth --datadir /home/{{USERNAME}}/node init /home/{{USERNAME}}/node/genesis.json"    
    failed_when: false
  
  - name: Get enode
    shell: "docker run -v /home/{{USERNAME}}:/home/{{USERNAME}} jmank88/geth --datadir /home/{{USERNAME}}/node js /home/{{USERNAME}}/enode.js"    
    register: enode_output      

  - set_fact:
      enode_from_host: "{{ enode_output.stdout[0:137] }}{{hostvars[inventory_hostname].ansible_host}}:30303"
  - debug:
      msg: "{{enode_from_host}}"
      
  - name: Copy config.toml for get
    template:
        src: ../templates/{{template_folder}}/config.toml.j2
        dest: /home/{{USERNAME}}/config.toml
- import_playbook: library/configure_run_updater.yml