---
- hosts: all
  become: true
  tasks:  
  - name: Include vars from docker.yml.
    include_vars:
      file: ../config/group_vars/docker.yml

  - name: Ensure old versions of Docker are not installed.
    package:
      name: '{{ item }}'
      state: absent
    with_items:
      - docker
      - docker-engine

  - name: Ensure dependencies are installed.
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Add Docker apt key.
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    register: add_repository_key
    ignore_errors: true

  - name: Ensure curl is present (on older systems without SNI).
    package: name=curl state=present
    when: add_repository_key|failed

  - name: Add Docker apt key (alternative for older systems without SNI).
    shell: "curl -sSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
    args:
      warn: no
    when: add_repository_key|failed

  - name: Add Docker repository.
    apt_repository:
      repo: "{{ docker_apt_repository }}"
      state: present
      update_cache: yes

  - name: Install Docker.
    package: name={{ docker_package }} state={{ docker_package_state }}

  - name: Ensure Docker is started and enabled at boot.
    service:
      name: docker
      state: started
      enabled: yes

  - name: Check current docker-compose version.
    command: docker-compose --version
    register: docker_compose_current_version
    changed_when: false
    failed_when: false

  - name: Delete existing docker-compose version if it's different.
    file:
      path: "{{ docker_compose_path }}"
      state: absent
    when: >
      docker_compose_current_version.stdout is defined
      and docker_compose_version not in docker_compose_current_version.stdout

  - name: Install Docker Compose (if configured).
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
      dest: "{{ docker_compose_path }}"
      mode: 0755
